### ISSUE TITLE
ModuleNotFoundError: No module named 'pydantic'

### ISSUE THREAD

**Issue by Pactortester** [yongchin0821/pywebreport#3]
https://github.com/yongchin0821/pywebreport/blob/b3de5fc9d2758bbb80c284796b5d994ab7436562/pywebreport/formatter.py#L8

![image](https://user-images.githubusercontent.com/29191106/183067894-ea580174-e70b-4efd-9b80-22fab7421d94.png)

**Comment by yongchin0821** [comment]
thx for this pr

**Comment by Pactortester** [comment]
https://github.com/yongchin0821/pywebreport/blob/bda6e406fca54d68fc8ef39117be3644d2a1646c/pywebreport/template/gen.py#L6
